const CASE_CONSTANTS = {
    IN_PROGRESS:0,
    SENT_TO_CREDIT:1,
    POST_SANCTION:2
}

const CASE_CONSTANTS_STATUS =new Object();
CASE_CONSTANTS_STATUS[CASE_CONSTANTS.IN_PROGRESS] ="On-boarding";
CASE_CONSTANTS_STATUS[CASE_CONSTANTS.SENT_TO_CREDIT] ="Sent to Credit";
CASE_CONSTANTS_STATUS[CASE_CONSTANTS.POST_SANCTION] ="Post Sanction";

export {CASE_CONSTANTS,CASE_CONSTANTS_STATUS}