import {StyleSheet, Dimensions} from 'react-native';
import Colors from '../../styles/Colors';
import Fonts from '../../styles/Fonts';
import ApplicationStyles from '../../styles/ApplicationStyles';

const width = Dimensions.get('window').width;
const height = Dimensions.get('window').height;

export default StyleSheet.create({
  gstnContainer: {
    ...ApplicationStyles.screen.container,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
  },
  nextRelContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    flex: 1,
  },
  navigationContainer: {
    flex: 1,
    position: 'absolute',
    height: '100%',
    width: '100%',
  },
  Container: {
    flex: 1,
    backgroundColor: Colors.contentBgColor,
  },
  uparrowContainer: {
    padding: 40,
  },
  downarrowContainer: {
    position: 'absolute',
    padding: 40,
    bottom: 0,
  },
  imgLegal: {
    width: 79,
    height: 81,
    alignSelf: 'center',
    marginBottom: 30,
  },
  comingSoonTitle: {
    color: '#4a4a4a',
    fontFamily: 'Helvetica',
    fontSize: 18,
    fontWeight: '700',
    alignSelf: 'center',
    marginBottom: 5,
  },
  comingSoonDesc: {
    color: '#6b6b6b',
    fontFamily: 'Helvetica',
    fontSize: 18,
    alignSelf: 'center',
  },
  refFormContainer: {
    backgroundColor: Colors.contentBgColor,
    width: '73%',
  },
  documentStatusContainer: {
    backgroundColor: Colors.white,
    width: '27%',
    height: height,
  },
  refHeaderName: {
    fontSize: 12,
    color: '#9c9ea0',
    fontFamily: 'Helvetica',
  },
  refHeaderValue: {
    //...Fonts.style.normal,
    fontSize: 14,
    color: Colors.text,
    marginTop: 5,
    fontWeight: 'bold',
    fontFamily: 'Helvetica',
  },
  addressWidget: {
    flexDirection: 'row',
    marginVertical: 40,
    justifyContent: 'space-between',
    borderBottomWidth: 0.5,
    borderBottomColor: '#c7c8ca',
    paddingBottom: 10,
    // width:'97%',
    marginLeft: 15,
  },
  icAddressWidget: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  addressField: {
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: width / 2,
  },
  addressLabel: {
    fontFamily: 'Helvetica',
    color: Colors.text,
    ...Fonts.style.normal,
  },
  icAddress: {
    width: 22,
    height: 22,
    position: 'absolute',
    right: -15,
  },
  addressText: {
    color: '#58595b',
    fontFamily: 'Helvetica',
    fontSize: 14,
    fontWeight: 'bold',
  },
  btnSaveDetails: {
    width: 150,
    height: 40,
    //marginTop:20,
    backgroundColor: '#9d1d28',
    color: '#fff',
    fontFamily: 'Helvetica',
    fontSize: 14,
    fontWeight: '700',
    padding: 10,
    textAlign: 'center',
    borderRadius: 20,
  },
  title: {
    ...Fonts.style.h1,
    color: Colors.text,
    fontWeight: 'bold',
    marginVertical: 40,
  },
  addGurantorText: {
    //...Fonts.style.normal,
    fontSize: 14,
    color: Colors.text,
    fontFamily: 'Helvetica',
    fontWeight: 'bold',
    paddingLeft: 8,
  },
  container: {
    flex: 1,
    paddingTop: 30,
    // backgroundColor: '#fff',
  },
  topHeading: {
    paddingLeft: 10,
    fontSize: 20,
  },
  header: {
    backgroundColor: '#fff',
    padding: 16,
    elevation: 5,
    marginBottom: 20,
    width: '92%',
    alignSelf: 'center',
  },
  headerText: {
    fontSize: 16,
    fontWeight: '500',
  },
  separator: {
    height: 0.5,
    backgroundColor: '#808080',
    width: '95%',
    marginLeft: 16,
    marginRight: 16,
  },
  text: {
    fontSize: 16,
    color: '#606070',
    padding: 10,
  },
  content: {
    // paddingBosubcategoryom: 10,
    paddingLeft: 10,
    paddingRight: 10,
    backgroundColor: '#fff',
  },
  editView: {
    backgroundColor: '#fff',
    paddingTop: 20,
    paddingRight: 20,
    paddingBottom: 20,
    elevation: 1,
    //marginBottom: 10,
    width: '92%',
    marginBottom: 10,
    borderRadius: 1,
    borderColor: '#e2e3e3',
    borderWidth: 1,
    alignSelf: 'center',
  },
  addView: {
    backgroundColor: '#fff',
    paddingTop: 20,
    paddingRight: 20,
    paddingBottom: 20,
    marginTop:70,
    //marginBottom: 10,
    width: '95%',
    // marginBottom: ,
    alignSelf: 'center',
    backgroundColor:'#00f'
  },
  radioContainer: {
    flexDirection: 'row',
    marginTop: 5,
    marginLeft: 0,
  },
  radioWidget: {
    flexDirection: 'row',
    marginRight: 30,
  },
  radioButton: {
    width: 30,
    height: 30,
    borderColor: Colors.text,
  },
  radioLabel: {
    ...Fonts.style.normal,
    color: Colors.darken,
    fontFamily: 'Helvetica',
    lineHeight: 26,
  },
  btnWithBorder: {
    width: 150,
    height: 40,
    backgroundColor: Colors.white,
    color: Colors.primary,
    fontFamily: 'Helvetica',
    fontSize: 14,
    fontWeight: 'bold',
    padding: 10,
    textAlign: 'center',
    borderRadius: 20,
    borderColor: Colors.primary,
    borderWidth: 1,
  },
  btnSaveDetails: {
    width: 150,
    height: 40,
    //marginTop:20,
    backgroundColor: '#9d1d28',
    color: '#fff',
    fontFamily: 'Helvetica',
    fontSize: 14,
    fontWeight: '700',
    padding: 10,
    textAlign: 'center',
    borderRadius: 20,
  },
  btnSaveDetailsDisable:{
    width:150,
    height:40,
    backgroundColor: '#ba636a',
    color:'#fff',
    fontFamily: "Helvetica",
    fontSize:14,
    fontWeight:'700',
    padding:10,
    textAlign:'center',
    borderRadius:20
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 50,
    marginLeft:68,
    marginRight:40,
    alignItems: 'center',
  },
  modalTitle: {
    color: Colors.text,
    fontFamily: 'Helvetica',
    fontSize: 18,

    fontWeight: 'bold',
  },
  modalOverlayBtn:{
    width:'100%',
    height:'100%'
  },
  modalOverlay:{
    backgroundColor:'rgba(0,0,0,0.5)',
    position:'absolute',
    left:0,
    right:0,
    bottom:0,
    top:0
  },
});
